# /your/project/vagrant/provisioning/roles/example/tasks/main.yml
---

- name: Obtener GPG 
  rpm_key:
    state: present
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
  

- name: Touch a file, elastic.repo
  file:
    path: /etc/yum.repos.d/elastic.repo
    state: touch
    mode: u=rwx,g=rw,o=r
     

- name: add conf
  blockinfile: 
    state: present
    insertafter: EOF
    dest: /etc/yum.repos.d/elastic.repo
    content: |
      [elastic-7.x]
      name=Elastic repository for 7.x packages
      baseurl=https://artifacts.elastic.co/packages/7.x/yum
      gpgcheck=1
      gpgkey=https://artifacts.elastic.co/GPG-KEY-elasticsearch
      enabled=1
      autorefresh=1
      type=rpm-md
            

- name: Install hearthbeat
  yum:
    name: heartbeat-elastic
    state: latest




