# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure("2") do |config|

  config.vm.define "vm1" do |vm1|
    vm1.vm.hostname = "challenge"
    vm1.vm.box = "bento/centos-7.6"
    config.ssh.insert_key = 'false'
    vm1.vm.network "private_network", ip: "198.163.33.10"
    
    vm1.vm.provider "virtualbox" do |vb|
      vb.name = "vm1"
      vb.gui = false
      vb.memory = "1024"
      vb.cpus = 1
    end

  # Ansible provisioner.
    config.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook.yml"
      ansible.inventory_path = "inventory"
      ansible.sudo = true
    end
  end

end

 
